// TENER CUIDADO CON LA FECHA Y HORA DEL MYSQL USAR LA HORA DE LA MAQUINA O
// USAR EL INTERVALO DE CONFIGURACIONES ZONAHORARIA
// MAX RESOLUCION 1018 X 623
program Sysalarm;

{%ToDo 'Sysalarm.todo'}

uses
  Forms,
  sysutils,
  system,
  windows,
  Uprincipal in 'Uprincipal.pas' {frmprincipal},
  Udm in 'Udm.pas' {DMAccesos: TDataModule},
  Ubusquedas in 'Ubusquedas.pas' {frmbusquedas},
  Uprospectos in 'Uprospectos.pas' {frmprospectos},
  Utipos in 'Utipos.pas' {frmtipos},
  Uestatus in 'Uestatus.pas' {frmstatus_eventos},
  Ufuentes in 'Ufuentes.pas' {frmfuentes},
  Utipo_servicios in 'Utipo_servicios.pas' {frmtipo_servicios},
  Uorigenes in 'Uorigenes.pas' {frmorigenes},
  Uareas in 'Uareas.pas' {frmareas},
  Upuestos in 'Upuestos.pas' {frmpuestos},
  Ugiros in 'Ugiros.pas' {frmgiros},
  about in 'about.pas' {frmAboutBox},
  Ucategorias in 'Ucategorias.pas' {frmcategorias},
  Uasig_eve_vend in 'Uasig_eve_vend.pas' {frmasig_even_vend},
  Utipos_actividades in 'Utipos_actividades.pas' {frmtipos_actividades},
  Uasig_eve_vend_admin in 'Uasig_eve_vend_admin.pas' {frmasig_even_vend1},
  Uproveedores in 'Uproveedores.pas' {frmproveedores},
  Udpto in 'Udpto.pas' {frmdpto},
  Utel in 'Utel.pas' {frmtel},
  Ucontactos in 'Ucontactos.pas' {frmcontacto},
  Uusuarios in 'Uusuarios.pas' {frmusuarios},
  Uarticulos in 'Uarticulos.pas' {frmarticulos},
  Urecursos in 'Urecursos.pas',
  Ufamilias in 'Ufamilias.pas' {frmfamilias},
  Udet_art in 'Udet_art.pas' {frmdet_art},
  Uclientes in 'Uclientes.pas' {frmclientes},
  Usplash in 'Usplash.pas' {frmsplash},
  Usecciones in 'Usecciones.pas' {frmsecciones},
  Usectores in 'Usectores.pas' {frmsectores},
  UBuscaArt in 'UBuscaArt.pas' {frmBuscaArt},
  Upedidos in 'Upedidos.pas' {frmpedidos},
  Uart_comp in 'Uart_comp.pas' {frmart_comp},
  UDatAdiCliente in 'UDatAdiCliente.pas' {frmDatAdiCliente},
  UOrdenCompra in 'UOrdenCompra.pas' {frmOrdenCompra},
  Uart_prov in 'Uart_prov.pas' {frmart_prov},
  IdSim in 'IdSim.pas',
  Ucompras in 'Ucompras.pas' {frmcompras},
  Ufrmrep_act_vend in 'Ufrmrep_act_vend.pas' {frmrep_act_vend},
  Urep_oport in 'Urep_oport.pas' {frmrep_oportu},
  Uparcializacion in 'Uparcializacion.pas' {frmparcializacion},
  Udmrep in 'Udmrep.pas' {DMREPORTES: TDataModule},
  Udatosfactura in 'Udatosfactura.pas' {frmdatosfactura},
  Urepllamadasxfuente in 'Urepllamadasxfuente.pas' {frmrepllamadasxfuente},
  Umoviles in 'Umoviles.pas' {frmmoviles},
  UColonias in 'UColonias.pas' {frmColonias},
  UColSector in 'UColSector.pas' {frmColSector},
  Ulineas in 'Ulineas.pas' {frmlineas},
  Uabogados in 'Uabogados.pas' {frmabogados},
  Ucontratos in 'Ucontratos.pas' {frmcontratos},
  Umotivo_cancel in 'Umotivo_cancel.pas' {frmmotivos_cancel},
  Urelacionborrar in 'Urelacionborrar.pas' {frmRelacionBorrar},
  UNotas in 'UNotas.pas' {frmnotas},
  Uotras_entradas in 'Uotras_entradas.pas' {frmotras_entradas},
  Uautentificacion in 'Uautentificacion.pas' {frmautentificacion},
  USqlViewer in 'USqlViewer.pas' {Viewer},
  Utipomovi in 'Utipomovi.pas' {frmtiposmovi},
  URemiFac in 'URemiFac.pas' {frmRemiFac},
  Ucobros in 'Ucobros.pas' {frmcobros},
  Uboletas_mensuales in 'Uboletas_mensuales.pas' {frmboletas_mensuales},
  UCancelaciones in 'UCancelaciones.pas' {frmcancelaciones},
  UInstMod in 'UInstMod.pas' {frmInstMod},
  Umoduloreportes in 'Umoduloreportes.pas' {frmmoduloreportes},
  UDevCompras in 'UDevCompras.pas' {frmDevCompras},
  Uremisionar_boletas in 'Uremisionar_boletas.pas' {frmremisionar_boletas},
  Uclie_cancel in 'Uclie_cancel.pas' {frmclie_cancel},
  UNotasCredito in 'UNotasCredito.pas' {frmNotasCredito},
  Uconcepto_es in 'Uconcepto_es.pas' {frmconcepto_es},
  Uaplica in 'Uaplica.pas' {frmaplica},
  UNoVistaVtasCliente in 'UNoVistaVtasCliente.pas' {frmNoVistaVtasCliente},
  UFacturacionLotes in 'UFacturacionLotes.pas' {frmFacturacionLotes},
  UfrmPagosDebe in 'UfrmPagosDebe.pas' {frmPagosDebe},
  Uconfiguraciones in 'Uconfiguraciones.pas' {frmconfiguraciones},
  Umensaje in 'Umensaje.pas' {frmmensaje},
  UFechaAplicacion in 'UFechaAplicacion.pas' {frmFechaAplicacion},
  UImpBoletas in 'UImpBoletas.pas' {frmImpBoletas},
  UMensajeCliente in 'UMensajeCliente.pas' {frmMensajeCliente},
  UImpFact in 'UImpFact.pas' {frmImpFact},
  UFactPed in 'UFactPed.pas' {frmFactPed},
  UGenBol in 'UGenBol.pas' {frmGenBol},
  Umonitoreo in 'Umonitoreo.pas' {frmMonitoreo},
  Umunicipios in 'Umunicipios.pas' {frmmunicipios},
  Utipoasentamientos in 'Utipoasentamientos.pas' {frmtipoasenta},
  Uestados in 'Uestados.pas' {frmestados},
  Ullegada_patrulleros in 'Ullegada_patrulleros.pas' {frmllegada_patrulleros},
  Uactivacion_positiva in 'Uactivacion_positiva.pas' {frmdetalles_pos},
  Uinyeccion_alarmas in 'Uinyeccion_alarmas.pas' {frminyeccion_alarmas},
  Umodems in 'Umodems.pas' {frmmodems},
  Ureports in 'Ureports.pas' {Reports_Alarmex},
  Uzonasdefault in 'Uzonasdefault.pas' {frmZonasDefault},
  Utipo_alarmas in 'Utipo_alarmas.pas' {frmtipoalarmas},
  UClasifServ in 'UClasifServ.pas' {frmClasificacionServicios},
  UEnviarCorreo in 'UEnviarCorreo.pas' {frmEnviarCorreo},
  UNoClienteZonas in 'UNoClienteZonas.pas' {frmNoZonasCliente},
  UReClasificacion in 'UReClasificacion.pas' {frmReClasificacion},
  Uturnos in 'Uturnos.pas' {frmturnos},
  Uservicios in 'Uservicios.pas' {frmservicios},
  UPrintLoteServicios in 'UPrintLoteServicios.pas' {frmPrintLoteServicios},
  UBuscarServ in 'UBuscarServ.pas' {frmBuscarServ},
  Upatrullaje in 'Upatrullaje.pas' {frmpatrulleros},
  Utravel in 'Utravel.pas' {frmtravel},
  Uquejas in 'Uquejas.pas' {frmQuejas},
  Urepdetalle in 'Urepdetalle.pas' {frmrepdetalle},
  UMantenimientos in 'UMantenimientos.pas' {frmmantenimientos},
  Upreguntapatrullero in 'Upreguntapatrullero.pas' {frmPreguntaPatrullero},
  utraficocliente in 'utraficocliente.pas' {frmtraficocliente},
  UunidadNegocio in 'UunidadNegocio.pas' {frmUnidadNegocio},
  Uabcmantenimientos in 'Uabcmantenimientos.pas' {frmabcmantenimientos},
  Ubonificaciones in 'Ubonificaciones.pas' {frmbonificaciones},
  UBorraVentas in 'UBorraVentas.pas' {frmBorraVentas},
  UBolAnuales in 'UBolAnuales.pas' {frmBolAnuales},
  UCambiaContratos in 'UCambiaContratos.pas' {frmCambiaContrato},
  Upedidospendientes in 'Upedidospendientes.pas' {frmpedidospendientes},
  UNoClientes in 'UNoClientes.pas' {frmNoClientes},
  UAperturaCierre in 'UAperturaCierre.pas' {frmAperturaCierre},
  UReasignaFacturas in 'UReasignaFacturas.pas' {frmReasignaFact},
  UCfgPresupuestos in 'UCfgPresupuestos.pas' {frmCfgPresup},
  UPresupuesto2 in 'UPresupuesto2.pas' {frmpresupuestos2},
  UHistoricoReportes in 'UHistoricoReportes.pas' {frmHistoricoReportes},
  UFormaPagoPre in 'UFormaPagoPre.pas' {frmFormasPagoPre},
  UCambiaExistencias in 'UCambiaExistencias.pas' {frmCambiaExistencias},
  UColUsuarios in 'UColUsuarios.pas' {frmColUsuarios},
  uMantenimientosSys in 'uMantenimientosSys.pas' {frmMantenimientosSys},
  URequisiciones in 'URequisiciones.pas' {frmRequisiciones},
  UCambs in 'UCambs.pas' {frmCabms},
  URepLlamXFuente in 'URepLlamXFuente.pas' {frmLlamXFuente},
  URepAsigOrig in 'URepAsigOrig.pas' {frmRepAsigOrig},
  UCambiaSaldos in 'UCambiaSaldos.pas' {frmCambiaSaldos},
  Uprotocolos in 'Uprotocolos.pas' {frmProtocolos},
  UConversionProtocolos in 'UConversionProtocolos.pas' {frmConversionProtocolos},
  UPasarColonias in 'UPasarColonias.pas' {frmPasarColonias},
  UExClientes in 'UExClientes.pas' {frmExClientes},
  UExDatosfactura in 'UExDatosfactura.pas' {frmExDatosfactura},
  USectoresVencidos in 'USectoresVencidos.pas' {frmsectoresvencidos},
  UBuscaManuales in 'UBuscaManuales.pas' {frmBuscaManual},
  UMinuta in 'UMinuta.pas' {frmMinuta},
  fpresupuesto in 'fpresupuesto.pas' {Frame1: TFrame},
  UOrdenes in 'UOrdenes.pas' {frmOrdenes},
  USenalesOpenClose in 'USenalesOpenClose.pas' {frmSenalesOpenClose},
  Utest in 'Utest.pas' {frmtest},
  UCambioFactura in 'UCambioFactura.pas' {frmCambioFactura},
  UAutorizacionCambios in 'UAutorizacionCambios.pas' {frmAutorizacionCambios},
  UFacturacionOportunidad in 'UFacturacionOportunidad.pas' {frmFacturacionOportunidad},
  Ureportes in 'Ureportes.pas',
  uComisionistas in 'uComisionistas.pas' {frmComisionistas},
  UMediaFiliacion in 'UMediaFiliacion.pas' {frmMediaFiliacion},
  UDesaplicarNC in 'UDesaplicarNC.pas' {frmDesaplicarNC},
  URepClientes in 'URepClientes.pas' {frmRepClientes},
  UMinutaMensual in 'UMinutaMensual.pas' {frmMinutaMensual},
  UMarcacionCobranza in 'UMarcacionCobranza.pas' {frmMarcacionCobranza},
  UMinutaGerencial in 'UMinutaGerencial.pas' {frmMinutaGerencial},
  LoginWindow_U in 'LoginWindow_U.pas' {LoginWindow},
  UCometarios in 'UCometarios.pas' {frmcomentarios},
  Utips in 'Utips.pas' {frmtips},
  UAgendaTelefonica in 'UAgendaTelefonica.pas' {frmagendatelefonica},
  UDatosFactOPort in 'UDatosFactOPort.pas' {frmDatosFactOport},
  UGraficas in 'UGraficas.pas' {frmgraficas},
  URepRecHumanos in 'URepRecHumanos.pas' {frmRepRecHumanos},
  URepMultiples in 'URepMultiples.pas' {frmRepMultiples},
  URepCobranza in 'URepCobranza.pas' {frmRepCobranza},
  URep_llamadastmk in 'URep_llamadastmk.pas' {frmrepllamadastmk},
  USalidaInventario in 'USalidaInventario.pas' {frmSalidaInventario},
  URepServicios in 'URepServicios.pas' {frmRepServicios},
  Umesesremision in 'Umesesremision.pas' {frmmesesremision},
  URepCentral in 'URepCentral.pas' {frmRepCentral},
  UNotasActivPositivas in 'UNotasActivPositivas.pas' {frmnotasactivpositivas},
  UConfiguracionesXConcepto in 'UConfiguracionesXConcepto.pas' {frmConfiguracionesXConcepto},
  UBolNoImp in 'UBolNoImp.pas' {frmBolNoImp},
  Uubicacion in 'Uubicacion.pas' {frmubicacion},
  UEnviaPromosion in 'UEnviaPromosion.pas' {frmEnviaPromosion},
  UCostos_Servicios in 'UCostos_Servicios.pas' {frmcostosservicios},
  Ureporteestadisticas in 'Ureporteestadisticas.pas' {frmreporteestadisticas},
  UTCPComCliente in 'UTCPComCliente.pas',
  USeguimientoAbogado in 'USeguimientoAbogado.pas' {frmseguimientoabogado},
  UEvaluacionDesempeno in 'UEvaluacionDesempeno.pas' {frmEvaluacionDesempeno},
  UMetasCobranza in 'UMetasCobranza.pas' {frmMetasCobranza},
  URemisionesAnuales in 'URemisionesAnuales.pas' {frmremisionesanuales},
  UNoNotasCredito in 'UNoNotasCredito.pas' {frmNoNotasCredito},
  UVistaVtasCliente in 'UVistaVtasCliente.pas' {frmVistaVtasCliente},
  Umotivocancelapedidos in 'Umotivocancelapedidos.pas' {frmmotcancelapedidos},
  Umotivocortesias in 'Umotivocortesias.pas' {frmmotivocortesias},
  UCuentascompartidas in 'UCuentascompartidas.pas' {frmCuentascompartidas},
  USaldarCortesias in 'USaldarCortesias.pas' {frmSaldarCortesias},
  UObrasProceso in 'UObrasProceso.pas' {frmObrasProceso},
  USectoresTurnos in 'USectoresTurnos.pas' {frmSectoresTurnos},
  uRepInstalaciones in 'uRepInstalaciones.pas' {frmRepInstalaciones},
  Uexportar in 'Uexportar.pas' {frmexportar},
  UusuariosDerechos in 'UusuariosDerechos.pas' {frmUsuariosDerechos},
  uRepVendedores in 'uRepVendedores.pas' {frmrepVendedores},
  Udmsincronizar in 'Udmsincronizar.pas' {DMSincronizar: TDataModule},
  UProgreso in 'UProgreso.pas' {frmprogreso},
  uDeshacerCancelacion in 'uDeshacerCancelacion.pas' {frmDeshacerCancelacion},
  uUsuarioActual in 'uUsuarioActual.pas' {frmUsuarioActual},
  URepEstandares in 'URepEstandares.pas' {frmRepEstandares},
  Ucliente_zonas in 'Ucliente_zonas.pas' {frmZonasCliente},
  uscanner in 'uscanner.pas' {frmscan},
  UExTel in 'UExTel.pas' {frmExTel},
  UExBuscarServ in 'UExBuscarServ.pas' {frmExBuscarServ},
  UExNotas in 'UExNotas.pas' {frmExNotas},
  uComunicador in 'uComunicador.pas' {frmComunicadores},
  UNotasSeg in 'UNotasSeg.pas' {frmnotasseg},
  uEntradasComunicador in 'uEntradasComunicador.pas' {frmEntradasComunicador},
  uRepLlamadasTel in 'uRepLlamadasTel.pas' {frmRepLlamadasTel},
  UAgendaGeneral in 'UAgendaGeneral.pas' {frmAgendaGeneral},
  uSolicitudesWeb in 'uSolicitudesWeb.pas' {frmSolicitudesWeb},
  UEmpresas in 'UEmpresas.pas' {frmempresas},
  uNotasTemp in 'uNotasTemp.pas' {frmNotasTemp},
  URepCaja in 'URepCaja.pas' {frmRepCaja},
  uFELog in 'uFELog.pas' {frmFELog},
  uFERegresaARemision in 'uFERegresaARemision.pas' {frmFERegresarARemision},
  UAsigFactPedFE in 'UAsigFactPedFE.pas' {frmAsigFactPedFE},
  UCancelacionesFE in 'UCancelacionesFE.pas' {frmCancelacionesFE},
  UCobrosFE in 'UCobrosFE.pas' {frmCobrosFE},
  UFacturacionLotesFE in 'UFacturacionLotesFE.pas' {frmFacturacionLotesFE},
  UNotasCreditoFE in 'UNotasCreditoFE.pas' {frmNotasCreditoFE},
  ucancelarEdixCFD in 'ucancelarEdixCFD.pas' {frmcancelarEdixFE},
  uRegresarARemision in 'uRegresarARemision.pas' {frmRegresarARemision},
  uservicios_esp in 'uservicios_esp.pas' {frmservicios_esp},
  uDeshacerHistorico in 'uDeshacerHistorico.pas' {frmDeshacerHistorico},
  WS_Infomensaje in 'WS_Infomensaje.pas',
  UNotasCreditoHist in 'UNotasCreditoHist.pas' {frmNotasCreditoHist},
  UBuroCredito in 'UBuroCredito.pas',
  uActualizarCategorias in 'uActualizarCategorias.pas' {frmActualizarCategorias},
  udptocategorias in 'udptocategorias.pas' {frmdptoscategorias},
  uprovtel in '..\SysalarmReporteador\uprovtel.pas' {frmprovtel},
  uFoliosUsuarios in 'uFoliosUsuarios.pas' {frmFoliosUsuarios},
  uvolantes in 'uvolantes.pas' {frmvolantes},
  Uboletas_mensualesElectronicas in 'Uboletas_mensualesElectronicas.pas' {frmboletas_mensualesElectronicas},
  UFacturacionLotesFECus in 'UFacturacionLotesFECus.pas' {frmFacturacionLotesFECus};

//UBuroCredito in 'UBuroCredito.pas';

var mango:integer;
{$R *.res}

begin
 Mango:=FindWindow(nil,'Sistema para el control de Alarmex3');
  if mango <> 0 then
   begin
    application.MessageBox('Ya se esta ejecutando este programa','Aviso',mb_iconinformation);
    application.Terminate;
   end
  else
   begin
  Application.Initialize;
  ShortDateFormat := 'yyyy/mm/dd';
  frmSplash := TfrmSplash.Create(Application); frmSplash.Showmodal; frmSplash.Update;
  Application.Title := 'Sistema para el control de Alarmex';
  Application.CreateForm(Tfrmprincipal, frmprincipal);
  Application.CreateForm(TDMAccesos, DMAccesos);
  Application.CreateForm(Tfrmbusquedas, frmbusquedas);
  Application.CreateForm(Tfrmtel, frmtel);
  Application.CreateForm(Tfrmcontacto, frmcontacto);
  Application.CreateForm(TfrmBuscaArt, frmBuscaArt);
  Application.CreateForm(TDMREPORTES, DMREPORTES);
  Application.CreateForm(Tfrmnotas, frmnotas);
  Application.CreateForm(Tfrmautentificacion, frmautentificacion);
  Application.CreateForm(Tfrmmensaje, frmmensaje);
  Application.CreateForm(TfrmPreguntaPatrullero, frmPreguntaPatrullero);
  Application.CreateForm(TLoginWindow, LoginWindow);
  Application.CreateForm(Tfrmmesesremision, frmmesesremision);
  Application.CreateForm(Tfrmubicacion, frmubicacion);
  Application.CreateForm(Tfrmreporteestadisticas, frmreporteestadisticas);
  Application.CreateForm(TDMSincronizar, DMSincronizar);
  Application.CreateForm(Tfrmprogreso, frmprogreso);
  Application.CreateForm(Tfrmnotasseg, frmnotasseg);
  frmSplash.Hide;
  frmSplash.Free;
  Application.Run;
 end;
end.

